-- MySQL Script generated by MySQL Workbench
-- 08/01/16 21:53:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbLogger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbLogger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbLogger` DEFAULT CHARACTER SET utf8 ;
USE `dbLogger` ;

-- -----------------------------------------------------
-- Table `dbLogger`.`Loggers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbLogger`.`Loggers` (
  `cdLogger` INT NOT NULL AUTO_INCREMENT,
  `flStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cdLogger`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLogger`.`Instalacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbLogger`.`Instalacoes` (
  `cdInstal` INT NOT NULL,
  `dtIni` DATETIME NOT NULL,
  `dtFim` DATETIME NOT NULL,
  `vlLat` FLOAT NOT NULL,
  `vlLong` FLOAT NOT NULL,
  `NumCasa` INT NOT NULL,
  `dsRua` VARCHAR(50) NOT NULL,
  `dsSituacao` SMALLINT NOT NULL,
  `flVazamento` INT NOT NULL,
  `cdLogger` INT NOT NULL,
  PRIMARY KEY (`cdInstal`),
  INDEX `fk_Instalacoes_Loggers1_idx` (`cdLogger` ASC),
  CONSTRAINT `fk_Instalacoes_Loggers1`
    FOREIGN KEY (`cdLogger`)
    REFERENCES `dbLogger`.`Loggers` (`cdLogger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLogger`.`Subprojetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbLogger`.`Subprojetos` (
  `cdSubprojeto` INT NOT NULL,
  `dsNome` VARCHAR(45) NOT NULL,
  `dtIni` DATETIME NOT NULL,
  `dtFim` DATETIME NOT NULL,
  `dsSituacao` SMALLINT NULL,
  `cdInstal` INT NOT NULL,
  PRIMARY KEY (`cdSubprojeto`),
  INDEX `fk_Subprojetos_Instalacoes1_idx` (`cdInstal` ASC),
  CONSTRAINT `fk_Subprojetos_Instalacoes1`
    FOREIGN KEY (`cdInstal`)
    REFERENCES `dbLogger`.`Instalacoes` (`cdInstal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLogger`.`Projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbLogger`.`Projetos` (
  `cdProjeto` INT NOT NULL,
  `dsNome` VARCHAR(45) NOT NULL,
  `dtIni` DATETIME NOT NULL,
  `dtFim` DATETIME NOT NULL,
  `dsSituacao` SMALLINT NOT NULL,
  `cdSubprojeto` INT NOT NULL,
  PRIMARY KEY (`cdProjeto`),
  INDEX `fk_Projetos_Subprojetos_idx` (`cdSubprojeto` ASC),
  CONSTRAINT `fk_Projetos_Subprojetos`
    FOREIGN KEY (`cdSubprojeto`)
    REFERENCES `dbLogger`.`Subprojetos` (`cdSubprojeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbLogger`.`InstalacoesSituacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbLogger`.`InstalacoesSituacoes` (
  `cdInstalSit` INT NOT NULL,
  `dsNome` VARCHAR(45) NOT NULL,
  `cdInstal` INT NOT NULL,
  PRIMARY KEY (`cdInstalSit`),
  INDEX `fk_InstalacoesSituacoes_Instalacoes1_idx` (`cdInstal` ASC),
  CONSTRAINT `fk_InstalacoesSituacoes_Instalacoes1`
    FOREIGN KEY (`cdInstal`)
    REFERENCES `dbLogger`.`Instalacoes` (`cdInstal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
